# Generated by Django 6.0.4 on 2026-05-14 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_latest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latest',
            name='description',
        ),
    ]
