# Generated by Django 6.0.4 on 2026-05-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_remove_latest_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('model_name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='productimage/')),
            ],
        ),
        migrations.DeleteModel(
            name='Latest',
        ),
    ]
