# Generated by Django 6.0.4 on 2026-05-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_trind_delete_latest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trind',
            name='image',
            field=models.ImageField(upload_to='trind/'),
        ),
    ]
