# Generated by Django 6.0.4 on 2026-05-20 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_alter_trind_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
