# Generated by Django 6.0.4 on 2026-05-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppicks',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='toppicks',
            name='model_name',
            field=models.CharField(max_length=100),
        ),
    ]
